version: 0.2

env:
  variables:
    STACK_NAME: "application-stack4"
    TEMPLATE_FILE: "application-cfn.yaml"
    PARAMETERS: | 
                ParameterKey=VpcID,ParameterValue=vpc-0d5d4b0f4e6f895ad
                ParameterKey=AMIID,ParameterValue=ami-0750ad3fb18154b1b
                ParameterKey=SubnetID1,ParameterValue=subnet-05badfe3396ca4402
                ParameterKey=SubnetID2,ParameterValue=subnet-05a218529c1a9dc62 
                ParameterKey=ASGMinValue,ParameterValue=2 
                ParameterKey=ASGMaxValue,ParameterValue=10

phases:
  install:
    commands:
      - echo "Installing AWS CLI v2..."
      - curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
      - unzip awscliv2.zip
      - sudo ./aws/install --update
      - aws --version

  pre_build:
    commands:
      - echo "Checking AWS CLI version..."
      - aws --version
      - echo "Validating CloudFormation template..."
      - aws cloudformation validate-template --template-body file://${TEMPLATE_FILE}

  build:
    commands:
      - |
        if [ "$ACTION" == "deploy" ]; then
          echo "Deploying CloudFormation stack: $STACK_NAME..."
          aws cloudformation deploy --stack-name $STACK_NAME --template-file ${TEMPLATE_FILE} --parameter-overrides $(echo "${PARAMETERS}" | tr '\n' ' ') --capabilities CAPABILITY_IAM CAPABILITY_NAMED_IAM

        elif [ "$ACTION" == "destroy" ]; then
          echo "Destroying CloudFormation stack: $STACK_NAME..."
          aws cloudformation delete-stack --stack-name $STACK_NAME
          echo "Waiting for stack deletion to complete..."
          aws cloudformation wait stack-delete-complete --stack-name $STACK_NAME
          
        else
          echo "Invalid ACTION parameter. Use 'deploy' or 'destroy'."
          exit 1
        fi

  post_build:
    commands:
      - echo "CloudFormation operation ($ACTION) completed successfully."
