version: 0.2

env:
  variables:
    STACK_NAME: "application-stack"
    TEMPLATE_FILE: "application-cfn.yaml"
  parameter-store:
    PARAMETERS: |
                ParameterKey=VpcID,ParameterValue=vpc-0d5d4b0f4e6f895ad
                ParameterKey=AMIID,ParameterValue=ami-0db18496905e01e3d
                ParameterKey=SubnetID1,ParameterValue=subnet-05badfe3396ca4402
                ParameterKey=SubnetID2,ParameterValue=subnet-05a218529c1a9dc62
                ParameterKey=ASGMinValue,ParameterValue=2
                ParameterKey=ASGMaxValue,ParameterValue=10

phases:
  install:
    commands:
      - echo "Installing dependencies..."
      - pip install --upgrade awscli

  pre_build:
    commands:
      - echo "Checking AWS CLI version..."
      - aws --version
      - echo "Validating CloudFormation template..."
      - aws cloudformation validate-template --template-body file://${TEMPLATE_FILE}

  build:
    commands:
      - echo "Deploying CloudFormation stack..."
      - aws cloudformation deploy \
          --template-file ${TEMPLATE_FILE} \
          --stack-name ${STACK_NAME} \
          --region $AWS_REGION \
          --capabilities CAPABILITY_NAMED_IAM \
          --parameter-overrides $(echo "${PARAMETERS}" | tr '\n' ' ')

  post_build:
    commands:
      - echo "Deployment complete!"
      - echo "Getting stack outputs..."
      - aws cloudformation describe-stacks --stack-name ${STACK_NAME} --query "Stacks[0].Outputs"
