Parameters:
  EC2AMIID:
    Type: String
    Description: Enter your EC2 AMI ID based on your OS
    Default: ami-03814457ed908d8f6
  EC2KeyPairName:
    Type: String
    Description: Select your desired keypair
    Default: metrocanadakp
  EC2InstanceType:
    Type: String
    Description: Enter your EC2 Instance Type
    Default: t2.micro
    AllowedValues:  
      - t2.micro
      - t3.micro
      - t3.medium
  SubnetID:
    Type: String
    Description: Enter your SubnetID
    Default: subnet-05badfe3396ca4402
  SecurityGroupID:
    Type: String
    Description: Enter your SecurityGroupID
    Default: sg-003f511e812626256
    

  
Resources:
  MyEC2Instance: 
    Type: AWS::EC2::Instance
    Properties: 
      ImageId: !Ref EC2AMIID
      KeyName: !Ref EC2KeyPairName
      InstanceType: !Ref EC2InstanceType
      SecurityGroupIds: 
        - !Ref SecurityGroupID
      SubnetId: 
        !Ref SubnetID
      UserData:
        Fn::Base64: !Sub |
            #!/bin/bash
            yum install httpd php php-mysql -y
            sudo amazon-linux-extras enable php7.2
            sudo yum clean metadata
            sudo yum install php-cli php-fpm php-mysqlnd php-pdo php-mbstring
            yum update -y
            cd /var/www/html
            echo "healthy" > healthy.html
            wget https://wordpress.org/wordpress-6.7.1.tar.gz
            tar -xzf wordpress-6.7.1.tar.gz
            cp -r wordpress/* /var/www/html/
            rm -rf wordpress
            rm -rf wordpress-6.7.1.tar.gz
            chmod -R 755 wp-content
            chown -R apache:apache wp-content
            service httpd start
            chkconfig httpd on
